# Generated by Django 5.2.8 on 2025-11-11 17:53

import apps.comum.managers.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('codigo_interno', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'db_table': 'filiais',
            },
        ),
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(help_text='Nome do contratante', max_length=200)),
                ('cnpj', models.CharField(help_text='CNPJ com 14 dígitos (apenas números)', max_length=14, unique=True, validators=[apps.comum.managers.utils.validar_cnpj])),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional sobre o contratante', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o contratante está ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contratante',
                'verbose_name_plural': 'Contratantes',
                'db_table': 'contratantes',
                'constraints': [models.UniqueConstraint(fields=('nome', 'cnpj'), name='uniq_contratantes_nome_cnpj')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('razao_social', models.CharField(help_text='Razão social da empresa', max_length=200)),
                ('cnpj', models.CharField(help_text='CNPJ com 14 dígitos (apenas números)', max_length=14, unique=True, validators=[apps.comum.managers.utils.validar_cnpj])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EmpresaCNPJ',
                'verbose_name_plural': 'EmpresasCNPJ',
                'db_table': 'empresa_cnpj',
                'constraints': [models.UniqueConstraint(fields=('razao_social',), name='uniq_empresa_cnpj_razao_social'), models.UniqueConstraint(fields=('cnpj',), name='uniq_empresa_cnpj_cnpj')],
            },
        ),
    ]
