# Generated by Django 5.2.8 on 2025-11-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoContratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numero_contrato_interno', models.CharField(help_text='Numero do contrato internamente', max_length=20, unique=True)),
                ('numero_contrato_contratante', models.CharField(blank=True, help_text='Numero do contrato no registro da contratante, para caso de integrações', max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contratante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.contratante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('empresa_cnpj_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_empresa_cnpj', to='empresas.empresacnpj')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato Contratante',
                'verbose_name_plural': 'Contratos Contratantes',
                'db_table': 'contratos_contratantes',
            },
        ),
        migrations.CreateModel(
            name='ContratoFiliais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numero', models.CharField(help_text='Identificador unico do contrato', max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('contrato_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais_contrato', to='contratos.contratocontratante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('filial_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.filial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato Filial',
                'verbose_name_plural': 'Contratos Filiais',
                'db_table': 'contratos_filiais',
            },
        ),
        migrations.AddConstraint(
            model_name='contratocontratante',
            constraint=models.UniqueConstraint(fields=('numero_contrato_interno', 'contratante_id'), name='uniq_contrato_contratante_numero_interno_contratante'),
        ),
        migrations.AddConstraint(
            model_name='contratocontratante',
            constraint=models.UniqueConstraint(fields=('numero_contrato_contratante', 'contratante_id'), name='uniq_contrato_contratante_numero_contratante_contratante'),
        ),
        migrations.AddConstraint(
            model_name='contratofiliais',
            constraint=models.UniqueConstraint(fields=('numero', 'filial_id'), name='uniq_contrato_filial_numero_filial'),
        ),
        migrations.AddConstraint(
            model_name='contratofiliais',
            constraint=models.UniqueConstraint(fields=('contrato_id', 'numero'), name='uniq_contrato_filial_contrato_numero'),
        ),
    ]
