# Generated by Django 5.2.8 on 2025-11-12 20:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contratocontratante',
            name='uniq_contrato_contratante_numero_contratante_contratante',
        ),
        migrations.AddField(
            model_name='contratofiliais',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratofiliais',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='contratocontratante',
            constraint=models.UniqueConstraint(fields=('numero_contrato_interno', 'contratante_id'), name='uniq_contrato_contratante_numero_contratante_contratante'),
        ),
    ]
