# Generated by Django 5.2.8 on 2025-11-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('telefone_celular', 'Telefone Celular'), ('telefone_fixo', 'Telefone Fixo'), ('email', 'E-mail'), ('outro', 'Outro')], max_length=20)),
                ('valor', models.CharField(max_length=150)),
                ('principal', models.BooleanField(default=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contatos',
                'indexes': [models.Index(fields=['tipo'], name='contatos_tipo_6b7c54_idx'), models.Index(fields=['valor'], name='contatos_valor_f3793e_idx'), models.Index(fields=['content_type', 'object_id'], name='contatos_content_030244_idx'), models.Index(fields=['content_type', 'object_id', 'tipo'], name='contatos_content_e3a031_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'tipo', 'valor'), name='uniq_contatos_tipo_valor_entidade'), models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('content_type', 'object_id', 'tipo'), name='uniq_contato_principal_por_tipo_entidade')],
            },
        ),
    ]
